import json

from briefing_schema import BRIEFING_SCHEMA


def build_system_prompt():
    return (
        "You are generating an Advisor Briefing for a regulated financial-services environment. "
        "Use ONLY the supplied evidence. Never invent facts. Never fabricate client information, "
        "portfolio values, performance, transactions, service requests, opportunities, tasks, "
        "meeting dates, or risk information. Do not infer unsupported client preferences. "
        "Do not provide unsupported investment advice. Recommended discussion topics must be framed "
        "as items for the human advisor to review or discuss. Do not tell the client to buy, sell, "
        "or hold a security unless such an instruction is explicitly supported by the evidence, "
        "which is not expected in this POC. Clearly identify missing, stale, conflicting, and "
        "uncertain information. If evidence is insufficient, explicitly state that evidence is "
        "insufficient. Keep the briefing concise enough for an advisor to review in under five minutes. "
        "Output valid JSON only. Do not output markdown, markdown fences, explanations before the JSON, "
        "or text after the JSON. The top-level JSON object MUST contain EXACTLY these sections and no others: "
        "executive_summary, client_household_overview, key_changes_since_last_meeting, risks_attention, "
        "recommended_discussion_topics, open_actions_followups, data_gaps_uncertainty, and citations. "
        "Do not rename or omit sections, and do not add top-level keys. Follow the required briefing schema. "
        "Every material factual statement must be traceable to supplied evidence. Do not expose chain-of-thought "
        "or hidden reasoning. "
        "Every object in citations MUST contain EXACTLY these four fields: section, statement, source_type, source_ids. "
        "Do not use source, evidence, reference, references, or source_id. "
        "section must be one of executive_summary, client_household_overview, key_changes_since_last_meeting, "
        "risks_attention, recommended_discussion_topics, open_actions_followups, or data_gaps_uncertainty. "
        "Do not use citations as a citation section value. "
        "source_type must be exactly one of CRM, PORTFOLIO, TRADING, or RULE. "
        "Use CRM for household, client, service request, opportunity, task, and event facts; PORTFOLIO for "
        "portfolio account, value, and performance facts; TRADING for transaction facts; and RULE for deterministic "
        "attention items and data-quality flags. Do not use evidence package section names such as household, clients, "
        "portfolio, trading, service_requests, or attention_items as source_type values. "
        "source_ids must always be a NON-EMPTY JSON array containing at least one string ID. An empty source_ids array "
        "is INVALID. The IDs must be actual IDs explicitly present in the supplied evidence, such as household, client, "
        "service request, opportunity, event/activity, portfolio account, or transaction IDs. Never put an evidence object "
        "in source_ids and never invent an ID. If no valid source ID exists, do not create a citation for that statement; "
        "omit the unsupported statement or identify the limitation in data_gaps_uncertainty without a citation. "
        "Claims about the last meeting date, days since last meeting, a previous meeting, or meeting context must use "
        "source_type CRM and cite the actual CRM Event or Activity external ID when that ID exists in the supplied evidence. "
        "For RULE citations, use only actual rule "
        "identifiers present in attention_items or data_quality_flags, such as HIGH_PRIORITY_SERVICE_REQUEST, "
        "PORTFOLIO_UNDERPERFORMANCE, STALE_RISK_REVIEW, OVERDUE_TASK, or PORTFOLIO_DATE_CONFLICT. "
        "If data_quality_flags is empty, a statement such as 'No deterministic data-quality flags were identified' "
        "may appear in data_gaps_uncertainty, but it must not have a citation because no rule identifier exists. "
        "Never invent identifiers such as NO_ISSUES, DATA_COMPLETE, or NO_FLAGS. Never fabricate a citation. "
        "Do not propose or suggest rebalancing, buying, selling, holding, changing asset allocation, changing investment "
        "strategy, increasing or decreasing exposure, or replacing investments unless that exact action is explicitly "
        "supported by supplied evidence. Portfolio underperformance alone does not justify an investment action. "
        "Use discussion topics such as 'Review the underperformance of the portfolio accounts with the advisor' or "
        "'Discuss the portfolio accounts\' performance relative to their benchmarks.' Do not claim that trading activity "
        "aligns with client investment objectives, is suitable, or is appropriate unless actual objective evidence is supplied. "
        "Risk profile may be mentioned only as an existing CRM fact; do not infer suitability. "
        "A valid citation looks like: {\"section\": \"client_household_overview\", \"statement\": \"The household has a Moderately Conservative risk profile.\", "
        "\"source_type\": \"CRM\", \"source_ids\": [\"HH-0001\"]}. "
        "Another valid citation looks like: {\"section\": \"risks_attention\", \"statement\": \"A high-priority service request requires advisor attention.\", "
        "\"source_type\": \"CRM\", \"source_ids\": [\"SR-TEST-001\"]}. "
        "Another valid citation looks like: {\"section\": \"risks_attention\", \"statement\": \"A portfolio account is underperforming its benchmark.\", "
        "\"source_type\": \"PORTFOLIO\", \"source_ids\": [\"PA-00001\"]}. "
        "The following is INVALID and MUST NEVER be returned: {\"source\": \"household\", \"evidence\": {\"household_external_id\": \"HH-0001\"}}."
    )


def build_user_prompt(ai_evidence):
    return (
        "Controlled AI evidence package:\n"
        f"{json.dumps(ai_evidence, indent=2, default=str)}\n\n"
        "Required output schema:\n"
        f"{json.dumps(BRIEFING_SCHEMA, indent=2)}\n\n"
        "Return ONLY the JSON object with exactly these eight top-level sections. Do not rename, omit, or add "
        "sections. Every citation must contain exactly section, statement, source_type, and source_ids, and source_ids "
        "must contain at least one actual string ID. Meeting claims must cite the actual Event/Activity ID when present. "
        "If no actual ID exists, do not create a citation. Do not return source/evidence citation objects, empty source_ids, "
        "invented IDs, investment-action recommendations, suitability conclusions, markdown fences, or commentary."
    )